{% set version = "0.5.10.20250401" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: types-jack-client
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-jack-client/types_jack_client-{{ version }}.tar.gz
  sha256: 21b3fb63b32178c840fcced98114b440380ef5f47cea851f5040f3a6af490cf1

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy
    - python >={{ python_min }}
    - types-cffi

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/jack-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for JACK-Client
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
