{% set version = "0.5.10.20260223" %}

package:
  name: types-jack-client
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-jack-client/types_jack_client-{{ version }}.tar.gz
  sha256: be0db8f66aa960932fd28d1752d3ef576c5cffc7dc6ae9edb807098347879445

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=77.0.3
  run:
    - numpy
    - python >={{ python_min }}
    - types-cffi

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/jack-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for JACK-Client
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
