{% set name = "types-JACK-Client" %}
{% set version = "0.5.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-JACK-Client-{{ version }}.tar.gz
  sha256: 65eda1deae4cb461aaa8ae4372ea4e30b0b44664d9b8152917713f116e1fd3ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/jack-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for JACK-Client
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
